### ISSUE TITLE
请教一下关于子包发布的问题

### ISSUE THREAD

**Issue by jeff-fe** [illa-family/illa-design#597]
### Description

无

### Link to Reproduction

 无

### Steps to reproduce

问题请教

### ILLA Design Version

1.6.4

### Browser

93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

问题1：想要发布全部子包，是执行什么命令发布的？可以一次性发版全部包吗？
问题2：例如一个场景 包@illa-design/select 需要升级，但是它依赖 @illa-design/input ,而且@illa-design/input也需要修改。那么开发调试的时候是不是需要先升级发版@illa-design/input，然后在@illa-design/select重新安装之后，这样才能再调试？

**Comment by AruSeito** [comment]
回答1：您好，发包和升级包所有对应的版本都是通过 [changeset](https://github.com/changesets/changesets)，一个命令即可全部发包或者部分发包
回答2：直接在本地按需修改就可以，然后最终通过 changeset 一次发包选择select 和 input 就可以了。 在开发过程中所有子包都会 link 到本地的代码，并不会走实际下载的 npm 包，具体细节您可以看一下 turbo。
